Add
liangjingkanji/BRV pull request #70
Opened 2021-11-26 06:43 UTC by dlisagod

修改addModels与addData的添加数据逻辑，使得models维持同一个对象

2021-11-26 07:41 UTC, liangjingkanji requested changes

2021-11-26 07:41 UTC, liangjingkanji commented on brv/src/main/java/com/drake/brv/BindingAdapter.kt
> +            this.models!!.isEmpty() -> {
一般情况下不要使用!!,  你可以使用`this.models?.isEmpty() == true`

2021-11-26 07:41 UTC, liangjingkanji commented on sample/src/main/java/com/drake/brv/sample/ui/fragment/RefreshFragment.kt
> +            Log.d(javaClass.simpleName, "${myList.size}")
不符合规范的日志

2021-11-26 07:41 UTC, liangjingkanji commented on sample/src/main/java/com/drake/brv/sample/ui/fragment/RefreshFragment.kt
> +    private val myList = mutableListOf<Any?>()
该PR不需要修改Demo示例代码

2021-11-26 07:41 UTC, liangjingkanji commented on brv/src/main/java/com/drake/brv/PageRefreshLayout.kt
> +                adjustAdapter.mutable.clear()
adjustAdapter.mutable可能抛出异常, 因为你判断全局变量是否为null结果可能被多线程修改导致判断无效

2021-11-26 08:02 UTC, dlisagod commented on brv/src/main/java/com/drake/brv/BindingAdapter.kt
> +            this.models!!.isEmpty() -> {
好的

2021-11-26 08:12 UTC, dlisagod commented on sample/src/main/java/com/drake/brv/sample/ui/fragment/RefreshFragment.kt
> +            Log.d(javaClass.simpleName, "${myList.size}")
我测试时候加的，那我去掉

2021-11-26 08:13 UTC, dlisagod commented on sample/src/main/java/com/drake/brv/sample/ui/fragment/RefreshFragment.kt
> +    private val myList = mutableListOf<Any?>()
我测试时候加的，那我去掉

2021-12-09 15:28 UTC, liangjingkanji approved these changes

2021-12-09 15:31 UTC, liangjingkanji commented
非常不错

2021-12-09 15:31 UTC, merged